"""
Core module for PyPacks.
"""

import os
import json


from .commands import say, _reset_commands, _current_commands



from typing import Callable, List, Tuple



class Mcmeta:
	"""
	Represents the pack.mcmeta metadata for a Minecraft datapack.
	"""
	def __init__(self, pack_format: int = 10, description: str = "Generated by PyPacks"):
		"""
		Args:
			pack_format (int): The pack format version.
			description (str): Description of the datapack.
		"""
		self.pack_format: int = pack_format
		self.description: str = description

	def to_dict(self) -> dict:
		"""
		Returns the mcmeta as a dictionary suitable for JSON serialization.
		"""
		return {
			"pack": {
				"pack_format": self.pack_format,
				"description": self.description
			}
		}


from typing import Callable, List, Tuple

class Datapack:
	"""
	Represents a Minecraft datapack and handles function registration and generation.
	"""
	def __init__(self, name: str, mcmeta: Mcmeta, output_dir: str = "."):
		"""
		Args:
			name (str): The name of the datapack folder.
			mcmeta (Mcmeta): The mcmeta metadata object.
			output_dir (str): Directory to generate the datapack in.
		"""
		self.name: str = name
		self.mcmeta: Mcmeta = mcmeta
		self.output_dir: str = output_dir
		self.functions: List[Tuple[str, Callable]] = []

	def mcfunction(self, name: str) -> Callable:
		"""
		Decorator to register a Python function as a Minecraft function file.
		Args:
			name (str): The namespace and function name (e.g., 'example:greet').
		Returns:
			Callable: The decorator for the function.
		"""
		def decorator(func: Callable) -> Callable:
			self.functions.append((name, func))
			return func
		return decorator

	def gen(self) -> None:
		"""
		Generates the datapack folder, pack.mcmeta, and all registered function files.
		"""
		datapack_path = os.path.join(self.output_dir, self.name)
		data_path = os.path.join(datapack_path, "data")
		# Use namespace from first function, or 'default'
		namespace = self.functions[0][0].split(":", 1)[0] if self.functions else "default"
		namespace_path = os.path.join(data_path, namespace, "functions")
		os.makedirs(namespace_path, exist_ok=True)

		# Write pack.mcmeta
		with open(os.path.join(datapack_path, "pack.mcmeta"), "w") as f:
			json.dump(self.mcmeta.to_dict(), f, indent=4)

		# Generate function files
		for fname, func in self.functions:
			_reset_commands()
			func()
			rel_name = fname.split(":", 1)[-1] + ".mcfunction"
			func_path = os.path.join(namespace_path, rel_name)
			with open(func_path, "w") as f:
				f.write("\n".join(_current_commands) + "\n")
